language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t umair1985/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true umair1985/docker-react npm run test -- --coverage
  